In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
from sklearn.datasets import load_breast_cancer
df = load_breast_cancer()

In [8]:
x = df.data
y = df.target

In [12]:
x = pd.DataFrame(x)

In [13]:
x

0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20     21      22      23       24       25      26  \
0    0.07871  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.05667  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.05999  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.09744  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.05883  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.05623  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         27      28       29  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 30 columns]

In [14]:
y = pd.DataFrame(y)

In [15]:
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [21]:
from sklearn.linear_model import LogisticRegression

# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=10000)
model.fit(x_train, y_train.values.ravel())

LogisticRegression(max_iter=10000)

In [22]:
from sklearn.metrics import accuracy_score

# Make predictions on the test set
y_pred = model.predict(x_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.965034965034965


In [23]:
from sklearn.metrics import confusion_matrix

# Confusion matrix for training data
y_train_pred = model.predict(x_train)
cm_train = confusion_matrix(y_train, y_train_pred)
print("Confusion Matrix for Training Data:")
print(cm_train)

# Confusion matrix for test data
cm_test = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix for Test Data:")
print(cm_test)

Confusion Matrix for Training Data:
[[148  10]
 [  6 262]]

Confusion Matrix for Test Data:
[[51  3]
 [ 2 87]]


In [25]:
from sklearn.metrics import classification_report

# Classification report for the training set
report_train = classification_report(y_train, y_train_pred)
print("Classification Report for Training Data:")
print(report_train)


# Classification report for the test set
report_test = classification_report(y_test, y_pred)
print("\nClassification Report for Test Data:")
print(report_test)

Classification Report for Training Data:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       158
           1       0.96      0.98      0.97       268

    accuracy                           0.96       426
   macro avg       0.96      0.96      0.96       426
weighted avg       0.96      0.96      0.96       426


Classification Report for Test Data:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        54
           1       0.97      0.98      0.97        89

    accuracy                           0.97       143
   macro avg       0.96      0.96      0.96       143
weighted avg       0.97      0.97      0.96       143



In [26]:
x_test

0      1       2       3        4        5        6        7       8   \
204  12.47  18.60   81.09   481.9  0.09965  0.10580  0.08005  0.03821  0.1925   
70   18.94  21.31  123.60  1130.0  0.09009  0.10290  0.10800  0.07951  0.1582   
131  15.46  19.48  101.70   748.9  0.10920  0.12230  0.14660  0.08087  0.1931   
431  12.40  17.68   81.47   467.8  0.10540  0.13160  0.07741  0.02799  0.1811   
540  11.54  14.44   74.65   402.9  0.09984  0.11200  0.06737  0.02594  0.1818   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
89   14.64  15.24   95.77   651.9  0.11320  0.13390  0.09966  0.07064  0.2116   
199  14.45  20.22   94.49   642.7  0.09872  0.12060  0.11800  0.05980  0.1950   
411  11.04  16.83   70.92   373.2  0.10770  0.07804  0.03046  0.02480  0.1714   
18   19.81  22.15  130.00  1260.0  0.09831  0.10270  0.14790  0.09498  0.1582   
390  10.26  12.22   65.75   321.6  0.09996  0.07542  0.01923  0.01968  0.1800   

          9   ...     20     21      22      23      24      25       26  \
204  0.06373  ...  14.97  24.64   96.05   677.9  0.1426  0.2378  0.26710   
70   0.05461  ...  24.86  26.58  165.90  1866.0  0.1193  0.2336  0.26870   
131  0.05796  ...  19.26  26.00  124.90  1156.0  0.1546  0.2394  0.37910   
431  0.07102  ...  12.88  22.91   89.61   515.8  0.1450  0.2629  0.24030   
540  0.06782  ...  12.26  19.68   78.78   457.8  0.1345  0.2118  0.17970   
..       ...  ...    ...    ...     ...     ...     ...     ...      ...   
89   0.06346  ...  16.34  18.24  109.40   803.6  0.1277  0.3089  0.26040   
199  0.06466  ...  18.33  30.12  117.90  1044.0  0.1552  0.4056  0.49670   
411  0.06340  ...  12.41  26.44   79.93   471.4  0.1369  0.1482  0.10670   
18   0.05395  ...  27.32  30.88  186.80  2398.0  0.1512  0.3150  0.53720   
390  0.06569  ...  11.38  15.65   73.23   394.5  0.1343  0.1650  0.08615   

          27      28       29  
204  0.10150  0.3014  0.08750  
70   0.17890  0.2551  0.06589  
131  0.15140  0.2837  0.08019  
431  0.07370  0.2556  0.09359  
540  0.06918  0.2329  0.08134  
..       ...     ...      ...  
89   0.13970  0.3151  0.08473  
199  0.18380  0.4753  0.10130  
411  0.07431  0.2998  0.07881  
18   0.23880  0.2768  0.07615  
390  0.06696  0.2937  0.07722  

[143 rows x 30 columns]

In [31]:
model.predict(x_test.iloc[[0]])

array([1])